cms/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-


from django.urls import path
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views

from cms import views as cms_views


urlpatterns = [

    path('', cms_views.home, name='base'),
    path('inicio/', cms_views.home, name='home'),

    path('acceso/', cms_views.custom_login, name='custom_login'),
    path('desconectar/', auth_views.LogoutView.as_view(), name='logout'),

    path('activacion/<uidb64>/<token>/', cms_views.activation, name='activation'),
    path('password_reset/', cms_views.password_reset, name='password_reset'),
    path('password_reset_form/<uidb64>/<token>/', cms_views.password_reset_form, name='password_reset_form'),

    # reset password form

    # Categorias Urls
    path('categorias/', cms_views.category_list, name='category_list'),
    path('categorias/crear', cms_views.category_create, name='category_create'),
    path('categorias/filtrar', cms_views.category_filter, name='category_filter'),
    path('categorias/scrap', cms_views.category_scrap, name='category_scrap'),
    path('categorias/upload', cms_views.category_upload, name='category_upload'),
    path('categorias/<int:id>/editar', cms_views.category_update, name='category_update'),
    path('categorias/<int:id>/ver', cms_views.category_view, name='category_view'),
    path('categorias/<int:id>/borrar', cms_views.category_delete, name='category_delete'),

    # Lugares Urls
    path('lugares/', cms_views.place_list, name='place_list'),
    path('lugares/crear', cms_views.place_create, name='place_create'),
    path('lugares/filtrar', cms_views.place_filter, name='place_filter'),
    path('lugares/scrap', cms_views.place_scrap, name='place_scrap'),

    path('lugares/upload', cms_views.place_upload, name='place_upload'),
    path('lugares/<int:id>/editar', cms_views.place_update, name='place_update'),
    path('lugares/<int:id>/ver', cms_views.place_view, name='place_view'),
    path('lugares/<int:id>/borrar', cms_views.place_delete, name='place_delete'),

    # Promos Urls
    path('promociones/', cms_views.promo_list, name='promo_list'),
    path('promociones/crear', cms_views.promo_create, name='promo_create'),
    path('promociones/filtrar', cms_views.promo_filter, name='promo_filter'),
    path('promociones/scrap', cms_views.promo_scrap, name='promo_scrap'),

    path('promociones/upload', cms_views.promo_upload, name='promo_upload'),
    path('promociones/<int:id>/editar', cms_views.promo_update, name='promo_update'),
    path('promociones/<int:id>/ver', cms_views.promo_view, name='promo_view'),
    path('promociones/<int:id>/borrar', cms_views.promo_delete, name='promo_delete'),

    # Precios Urls
    path('precios/', cms_views.price_list, name='price_list'),
    path('precios/crear', cms_views.price_create, name='price_create'),
    path('precios/filtrar', cms_views.price_filter, name='price_filter'),
    path('precios/scrap', cms_views.price_scrap, name='price_scrap'),

    path('precios/upload', cms_views.price_upload, name='price_upload'),
    path('precios/<int:id>/editar', cms_views.price_update, name='price_update'),
    path('precios/<int:id>/ver', cms_views.price_view, name='price_view'),
    path('precios/<int:id>/borrar', cms_views.price_delete, name='price_delete'),

    # Horarios Urls
    path('horarios/', cms_views.schedule_list, name='schedule_list'),
    path('horarios/crear', cms_views.schedule_create, name='schedule_create'),
    path('horarios/filtrar', cms_views.schedule_filter, name='schedule_filter'),
    path('horarios/scrap', cms_views.schedule_scrap, name='schedule_scrap'),

    path('horarios/upload', cms_views.schedule_upload, name='schedule_upload'),
    path('horarios/<int:id>/editar', cms_views.schedule_update, name='schedule_update'),
    path('horarios/<int:id>/ver', cms_views.schedule_view, name='schedule_view'),
    path('horarios/<int:id>/borrar', cms_views.schedule_delete, name='schedule_delete'),

    # Publicaciones Urls
    path('publicaciones/', cms_views.publication_list, name='publication_list'),
    path('publicaciones/crear', cms_views.publication_create, name='publication_create'),
    path('publicaciones/filtrar', cms_views.publication_filter, name='publication_filter'),
    path('publicaciones/scrap', cms_views.publication_scrap, name='publication_scrap'),

    path('publicaciones/upload', cms_views.publication_upload, name='publication_upload'),
    path('publicaciones/<int:id>/editar', cms_views.publication_update, name='publication_update'),
    path('publicaciones/<int:id>/ver', cms_views.publication_view, name='publication_view'),
    path('publicaciones/<int:id>/borrar', cms_views.publication_delete, name='publication_delete'),

    # Usuarios Urls
    path('usuarios/', cms_views.user_list, name='user_list'),
    path('usuarios/crear', cms_views.user_create, name='user_create'),
    path('usuarios/filtrar', cms_views.user_filter, name='user_filter'),
    path('usuarios/scrap', cms_views.user_scrap, name='user_scrap'),

    path('usuarios/upload', cms_views.user_upload, name='user_upload'),
    path('usuarios/<int:id>/editar', cms_views.user_update, name='user_update'),
    path('usuarios/<int:id>/ver', cms_views.user_view, name='user_view'),
    path('usuarios/<int:id>/borrar', cms_views.user_delete, name='user_delete'),

    # Imagenes Urls
    path('imagenes/', cms_views.image_list, name='image_list'),
    path('imagenes/crear', cms_views.image_create, name='image_create'),
    path('imagenes/filtrar', cms_views.image_filter, name='image_filter'),
    path('imagenes/scrap', cms_views.image_scrap, name='image_scrap'),

    path('imagenes/upload', cms_views.image_upload, name='image_upload'),
    path('imagenes/<int:id>/editar', cms_views.image_update, name='image_update'),
    path('imagenes/<int:id>/ver', cms_views.image_view, name='image_view'),
    path('imagenes/<int:id>/borrar', cms_views.image_delete, name='image_delete'),

    # Video Urls
    path('videos/', cms_views.video_list, name='video_list'),
    path('videos/crear', cms_views.video_create, name='video_create'),
    path('videos/filtrar', cms_views.video_filter, name='video_filter'),
    path('videos/scrap', cms_views.video_scrap, name='video_scrap'),

    path('videos/upload', cms_views.video_upload, name='video_upload'),
    path('videos/<int:id>/editar', cms_views.video_update, name='video_update'),
    path('videos/<int:id>/ver', cms_views.video_view, name='video_view'),
    path('videos/<int:id>/borrar', cms_views.video_delete, name='video_delete'),

    # Category API Urls
    path('rest_category_list/', cms_views.rest_category_list, name='rest_category_list'),
    path('rest_category_detail/', cms_views.rest_category_detail, name='rest_category_detail'),
    path('rest_category_final/', cms_views.rest_category_final, name='rest_category_final'),

    # Places API Urls
    #path('rest_places/<int:id>', cms_views.rest_place_list, name='rest_place_list'),
    path('rest_places/', cms_views.rest_place_list, name='rest_place_list'),

    # Places API Urls
    #path('rest_promos/<int:id>', cms_views.rest_promo_list, name='rest_promo_list'),
    path('rest_promos/', cms_views.rest_promo_list, name='rest_proms_list'),

    # Events API Urls
    #path('rest_events/<int:id>', cms_views.rest_event_list, name='rest_event_list'),
    path('rest_events/', cms_views.rest_event_list, name='rest_event_list'),

    # News API Urls
    #path('rest_news/<int:id>', cms_views.rest_new_list, name='rest_new_list'),
    path('rest_news/', cms_views.rest_new_list, name='rest_new_list'),

]




#

valladolid_movil/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static

from valladolid_movil import settings
from cms import urls as cms_urls
from cms import views as cms_views

admin.site.site_header = 'Valladolid Móvil CMS'
admin.autodiscover()


urlpatterns = [

    # Home
    path('', cms_views.home, name='base'),

    # Admin Urls
    path('admin/', admin.site.urls),

    # CMS Urls
    path('cms/', include((cms_urls, 'cms'), namespace='cms')),

    # Error Handler Urls
    #handler400 = 'cms_views.handler400'
    #handler403 = 'cms_views.handler403'
    #handler404 = 'cms_views.handler404'
    #handler500 = 'cms_views.handler500'

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

{% block extrahead %}
{% endblock %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Valladolid CMS</title>

    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Bootstrap DateTimePicker CSS -->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">-->

    <!-- TimePicker CSS-->
    <link rel="stylesheet" href="//jonthornton.github.io/jquery-timepicker/jquery.timepicker.css">

    <!-- Icons FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesomeicons.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block stylesheet %}
    {% endblock %}

  </head>
  <body>

    {% include 'navbar.html' %}

    {% include 'breadcrums.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <!-- jQuery JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Popper JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!--<script type="text/javascript" src='https://unpkg.com/popper.js/dist/umd/popper.min.js'></script>-->

    <!-- jQuery UI JS -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <!-- Moments JS -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>-->

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Bootstrap DateTimePicker JS -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>-->

    <!-- FontAwesome Icons -->
    <script src="{% static 'js/fontawesomeicons.js' %}"></script>

    <!-- TimePicker JS -->
    <script src="//jonthornton.github.io/jquery-timepicker/jquery.timepicker.js"></script>

    <!-- CKeditor -->
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <!-- Custom JS -->
    <script src="{% static 'js/functions.js' %}"></script>

    {% block javascript %}
    {% endblock javascript %}

  </body>
</html>

templates/carousel.html
<!-- Carousel -->
{% if images %}
  <p><b>Imágenes:</b></p>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for i in images %}
        {% if forloop.counter == 1 %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" class="active"></li>
        {% else %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}"></li>
        {% endif %}
      {% endfor %}
    </ol>
    <div class="carousel-inner">
      {% for image in images %}
        {% if forloop.counter == 1 %}
          <div class="carousel-item active">
            <img src="{{ image.imagen.url }}" class="d-block w-100 img-fluid" alt="">
          </div>
        {% else %}
          <div class="carousel-item">
            <img src="{{ image.imagen.url }}" class="d-block w-100 img-fluid" alt="">
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
{% else %}
    <img src="{{ element.imagen.url }}" class="d-block w-100 img-fluid" alt="">
{% endif %}

templates/create.html
{% load static %}
{% load cms_tags %}
{% load widget_tweaks %}


<!-- CKeditor -->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{% block javascript %}
  <script type="text/javascript">
    $( function() {
      $( ".timepicker" ).timepicker({
        timeFormat: 'H:i',
      });
    });
  </script>
{% endblock javascript %}


<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% get_url urls 'create' as element_create %}
    <form method="POST" action="{% url element_create %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {% if form %}
          {% include 'form.html' %}
        {% endif %}

        <!-- Formset Schedule -->
        {% if formset %}
          {% include 'formset.html' %}
        {% endif %}

      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-outline-primary">Crear</button>
      </div>
    </form>
  </div>
</div>

templates/delete.html
{% load cms_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">

    {% get_url urls 'delete' as element_delete %}
    <form method="POST" action="{% url element_delete element.id %}">
      {% csrf_token %}

    <div class="modal-header">
      <h4 class="modal-title">{{ title }}</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">

      <p>¿ Seguro que quieres borrarlo ?</p>
      {% include 'form.html' %}

    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-outline-danger">
        Borrar
      </button>
    </div>

    </form>

  </div>
</div>

templates/footer.html
<footer class="footer text-center">
  <div class="container">
    <span>VALLADOLID MOVIL © <script>document.write(new Date().getFullYear());</script> Todos los derechos reservados.</span><br>
    <span> { } with &hearts; by <a href="https://cg3innova.es/" target="_blank">CG3 Innova</a></span>
    <!--<ul>
      <li><a href="#" target="_blank">API</a></li>
      <li><a href="#">Legal</a></li>
      <li><a href="#">Únete</a></li>
      <li><a href="#">Contacto</a></li>
    </ul>-->
  </div>
</footer>

templates/form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>

    {{ field|add_class:"form-control" }}

    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <div">
        <img class="img-fluid" src="{% static 'img/valladolid_banner.jpg' %}" alt="">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
        <h2 class="text-center">CMS</h2>
				<p class="text-center">Software de gestión de contenido. Para organizar y actualizar el contenido de la aplicación móvil.</p>
				<p class="text-center"><a class="btn btn-default" target="_blank" href="https://cg3innova.es/">Ver detalles &raquo;</a></p>
			</div>
			<div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
				<h2 class="text-center">APP</h2>
				<p class="text-center">Dar a conocer todos los servicios de Valladolid Móvil a los usuarios./p>
        <p class="text-center"><a class="btn btn-default" target="_blank" href="https://cg3innova.es/">Ver detalles &raquo;</a></p>
			</div>
			<div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
				<h2 class="text-center">WEB</h2>
				<p class="text-center">Las mismas funcionalidades y características que la app pero a través del navegador.</p>
				<p class="text-center"><a class="btn btn-default" target="_blank" href="https://cg3innova.es/">Ver detalles &raquo;</a></p>
			</div>
		</div>
    <div class="row">
    </div>
	</div>
</div>
<hr>

{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Acceso a usuarios</h3>

        <form method="POST" action="{% url 'cms:custom_login' %}">
          {% csrf_token %}

          {% include 'form.html' %}

          <a href="{% url 'cms:password_reset' %}" class="btn btn-link btn-small">¿Olvidaste tu contraseña?</a>
          <button type="submit" class="btn btn-outline-primary">Acceder</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

templates/navbar.html
{% load static %}


<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'cms:home' %}">VALLADOLID MOVIL</a>
    </div>

    <div class="collapse navbar-collapse" id="generalMenu">

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:category_list' %}">Categorías</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:place_list' %}">Lugares</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:publication_list' %}">Publicaciones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:promo_list' %}">Promos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:price_list' %}">Precios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:schedule_list' %}">Horarios</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'cms:image_list' %}">Imagenes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:video_list' %}">Videos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cms:user_list' %}">Usuarios</a>
        </li>

        <li class="nav-item">
      <div class="dropdown">

        <button type="button" class="btn btn-outline-primary dropdown-toggle btn-sm" id="profileMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fas fa-user" style="font-size: 20px;"></span>
        </button>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileMenu">
          {% if not user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'cms:custom_login' %}">Acceder</a>
          {% else %}

            <a class="dropdown-item"
              <button type="button" onclick="return openCustomModal('{% url 'cms:user_view' user.id %}')" class="btn btn-outline-primary float-right btn-sm">
                {{ user.username }}
              </button>
            </a>
            <a class="dropdown-item" href="{% url 'cms:password_reset' %}">Cambiar Contraseña</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'cms:logout'%}">Cerrar Sesión</a>
          {% endif %}
        </div>
      </div>
      </li>

      </ul>

    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#generalMenu" aria-controls="generalMenu" aria-expanded="true" aria-label="Toggle navigation">
      <span class="fas fa-bars" style="font-size: 20px;"></span>
    </button>

  </div>
</nav>




<!-- -->

templates/password_reset.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Restaurar Contraseña</h3>

        <form method="POST" action="{% url 'cms:password_reset' %}">
          {% csrf_token %}

          <!--<div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
          <div class="form-group required"><label for="UserUsername">Correo</label><input name="data[User][username]" class="form-control" placeholder="@" type="text" id="UserUsername" required="required"/></div>
          <div class="form-group required"><label for="UserPassword">Contraseña</label><input name="data[User][password]" class="form-control" placeholder="********" type="password" id="UserPassword" required="required"/></div>
          <button type="submit" label="" class="btn btn-outline-primary">Entrar</button>
        </form>-->
          {% include 'form.html' %}

          <!--<a href="{% url 'cms:password_reset' %}" class="btn btn-link btn-small">¿Olvidaste tu contraseña?</a>-->

          <button type="submit" class="btn btn-outline-primary">Restablecer</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

templates/password_reset_form.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Restaurar Contraseña</h3>

        <form method="POST" action="{% url 'cms:password_reset_form' uidb64=user token=None %}">
          {% csrf_token %}

          <!--<div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
          <div class="form-group required"><label for="UserUsername">Correo</label><input name="data[User][username]" class="form-control" placeholder="@" type="text" id="UserUsername" required="required"/></div>
          <div class="form-group required"><label for="UserPassword">Contraseña</label><input name="data[User][password]" class="form-control" placeholder="********" type="password" id="UserPassword" required="required"/></div>
          <button type="submit" label="" class="btn btn-outline-primary">Entrar</button>
        </form>-->
          {% include 'form.html' %}

          <!--<a href="{% url 'cms:password_reset' %}" class="btn btn-link btn-small">¿Olvidaste tu contraseña?</a>-->

          <button type="submit" class="btn btn-outline-primary">Restablecer</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

templates/update.html
{% load static %}
{% load cms_tags %}


<!-- CKeditor -->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<div class="modal-dialog modal-lg">
  <div class="modal-content">

    {% get_url urls 'update' as element_update %}
    <form method="POST" action="{% url element_update element.id %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {% include 'form.html' %}

        <!-- Formset Schedule -->
        {% if formset %}
          {% include 'formset.html' %}
        {% endif %}

      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-outline-primary">Guardar</button>
      </div>
    </form>
  </div>
</div>

templates/view.html
{% load static %}
{% load cms_tags %}
{% load embed_video_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {% for key, value in element.fields_values.items %}
          <p><b>{{ key }}:</b> {{ value|safe }}</p>
        {% endfor %}

        {% include 'carousel.html' %}

        {% include 'video.html' %}

      </div>
  </div>
</div>